### PR TITLE
Added portuguese translation

### PR DESCRIPTION
**Pull request by sandroscosta**

### CODE REVIEW

**Comment by fnoks** [comment]
Thank you so much for all your translation contributions. I have already merged in another Portuguese translation PR, which is conflicting with your translations. Since I don't know Portugese I can't decide which translations are "best". If you think the pt.json from the other PR is OK (https://github.com/h5p/h5p-impressive-presentation/pull/10), you could close this one. If not, could you please resolve the conflicts, and I will merge it in?

**Comment by sandroscosta** [comment]
Much like American English and British English, Portuguese from Portugal and Portuguese from Brasil are a bit different in some ways. jnavroski translation is correct but gramatically it's not Portugal's Portuguese. As jnavroski was first, let the merged translation be the one active. I can correct some things if their wrong but he had the work so I don't wanna change it completely.

**Comment by jnavroski** [comment]
@fnoks @sandroscosta Is there a way to maintain both pt-pt and pt-br translations? Maybe sandroccosta can upload the pt.json (or pt-pt.json) and I can create the pt-br.json, but not sure if that would work.

**Comment by jnavroski** [comment]
I'm gonna close my Pull requests until this is solved. If it is okay for me to upload the pt-br files, @fnoks feel free to merge any pt translations that sandroscosta upload on top of the ones I did.

**Comment by sandroscosta** [comment]
I would love to work together with @jnavroski to translate everything to Portuguese, as much of the language is the same. It would also be much easier if one of us had already translate to pt. Only small changes would apply. @fnoks Is it possible to have pt-pt and pt-br like @jnavroski asks?

**Pull request closed without merging**
